### ISSUE TITLE
Network applet don't have a focus by default when the window to provide a password is open.

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mint21.2-beta#34] opened 2023-06-23 15:48 UTC
Network applet don't have a focus by default when the window to provide a password is open.

In previous versions, this behavior was default, and it was convenient for users, so I suggest bringing it back.

It should look like this, by default
![focus](https://github.com/linuxmint/mint21.2-beta/assets/23406555/7f6d52e1-a2be-41cd-ba71-9877c01bab5b)

**Comment by clefebvre** [comment] 2023-06-25 13:58
This is a regression since at least 21.

@mtwebster any idea?

**Comment by mtwebster** [comment] 2023-07-01 15:58
This is an issue with libnma:
https://gitlab.gnome.org/GNOME/libnma/-/issues/19
There's a WIP merge request to fix it: https://gitlab.gnome.org/GNOME/libnma/-/merge_requests/51

I'm not sure of any way we can address it short of maybe doing some sort of magic in our xapp gtk module..

**Comment by clefebvre** [comment] 2023-07-02 09:21
Ok this is upstream wontfix.

**Closed as completed by clefebvre** 2023-07-02 09:21 UTC
