### ISSUE TITLE
xreader: always maximize does not respect saved default settings

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21.2-beta#67] opened 2023-07-03 14:22 UTC
Version is Xreader 3.8.1 running in Cinnamon Edition 5.8.3.
Issue is: After setting "Save Current Settings as Default" when a letter size PDF file is open and then closed.  Upon opening a new letter size PDF file that has never been opened before it opens full screen instead of using the defaults.

This was not the behavior before.

Expected behavior is opening PDF files of the same page size the default size on the screen should be respected.
Instead I have to minimize and then choose "Expand Window to Fit" ... two additional steps.

**Comment by mtwebster** [comment] 2023-07-04 16:44
This is likely caused by https://github.com/linuxmint/xreader/pull/590.

Personally I lean towards maximizing by default but it may be better to prevent the original issue in the first place (making the window monitor-sized, but not maximized).

**Comment by Acheron17** [comment] 2023-07-04 17:04
Why can't the saved window state be used as before?  Especially since there is a menu item for it.  Perhaps add an option to always open with the saved window state?

**Comment by clefebvre** [comment] 2023-07-05 09:42
The bug report is valid imo. We need to address this regression. We should let people disable the "always start maximized" option (i.e. make it configurable).

**Comment by clefebvre** [comment] 2023-07-05 11:22
Fixed by https://github.com/linuxmint/xreader/commit/65a3e5f647f70e578f47176ed1dc554a6638e127 and https://github.com/linuxmint/xreader/commit/87bc2093fc21c95f898b1c12f2b12f60d6f684ff

**Closed as completed by clefebvre** 2023-07-05 11:22 UTC
Labels: confirmed
