### ISSUE TITLE
cinnamon: Wrong 'Gestures' icon with Papirus icon theme

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.2-beta#8] opened 2023-06-21 05:10 UTC
![papirus](https://github.com/linuxmint/mint21.2-beta/assets/68134588/f046217e-ff85-4c15-b8f0-163f182ceb2e)

Papirus, Papirus-Dark, Papirus-Light, ePapirus, ePapirus-Dark load Gestures with CS icon [lutris_counter-strike.svg apparently].

I don't know what version of the icon themes you are using LM 21.2, maybe you can update them. Checking Papirus has icons that Gestures could use: [1](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/a2a1b42a919d4dabd1c6759542cd517d2e30b4c9/Papirus/48x48/apps/mouse-touchpad-clicking.svg?plain=1) / [2](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/a2a1b42a919d4dabd1c6759542cd517d2e30b4c9/Papirus/48x48/apps/mouse-touchpad-gestures.svg?plain=1#L4)

PS. Maybe you could add the [Tela](https://github.com/vinceliuice/Tela-icon-theme) icon [theme](https://www.pling.com/p/1279924/), it is very complete.

**Comment by axel358** [comment] 2023-06-21 12:26
this is one of the reasons why i don't see preinstalling other icon packs is a good thing. It becomes your responsibility to test everything u do against all of them. The more u have the more likely this issues are to happen. In my case i use Tela-circle so i end up having to remove all these other icon packs that i don't use n only make the iso bigger

**Comment by axel358** [comment] 2023-06-21 12:29
That minimize icon looks like Downloads to me

**Comment by mtwebster** [comment] 2023-06-21 15:44
There is a correctly-named icon in the hicolor icon folder, as there should be, as a fallback for themes lacking it. The issue is Gtk is incorrectly attempting to shorten the name (cs-gestures -> cs) in order to find a match first in the user's current theme, and comes up with the counterstrike icon (cs)

**Comment by clefebvre** [comment] 2023-06-22 08:05
Fixed in master.

**Closed as completed by clefebvre** 2023-06-22 08:05 UTC
