### ISSUE TITLE
driver-manager: No drivers needed

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint21.2-beta#66] opened 2023-07-02 05:39 UTC
Hi,

I did an in-place upgrade from 21.1 to 21.2 Beta (Cinnamon).
When I go into Driver Manager, I do not see any display drivers for my nVidia GPU?
Any ideas?

nVidia proprietary display driver version 530.41.03 is installed and functioning 100%.

Everything works except Driver Manager?

```
System:
  Kernel: 6.1.0-1015-oem x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.3 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASUSTeK model: TUF GAMING X570-PLUS (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 4602 date: 02/23/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 5800X bits: 64 type: MT MCP arch: Zen 3 rev: 2 cache:
    L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 3414 high: 4567 min/max: 2200/4850 boost: enabled cores: 1: 3651 2: 3660
    3: 3654 4: 4567 5: 3652 6: 2200 7: 3698 8: 3653 9: 2200 10: 2200 11: 3653 12: 4539 13: 3659
    14: 3653 15: 3800 16: 2200 bogomips: 121376
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] vendor: Micro-Star MSI driver: nvidia
    v: 530.41.03 pcie: speed: 2.5 GT/s lanes: 16 ports: active: none off: HDMI-A-1
    empty: DP-1,DP-2,DP-3 bus-ID: 0a:00.0 chip-ID: 10de:2504
  Device-2: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 1-2.4:5
    chip-ID: 046d:082d
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-0 res: 1920x1080 dpi: 93 diag: 604mm (23.8")
  OpenGL: renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2 v: 4.6.0 NVIDIA 530.41.03
    direct render: Yes
Audio:
  Device-1: NVIDIA vendor: Micro-Star MSI driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s
    lanes: 16 bus-ID: 0a:00.1 chip-ID: 10de:228e
  Device-2: AMD Starship/Matisse HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel pcie:
    speed: 16 GT/s lanes: 16 bus-ID: 0c:00.4 chip-ID: 1022:1487
  Device-3: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 1-2.4:5
    chip-ID: 046d:082d
  Sound Server-1: ALSA v: k6.1.0-1015-oem running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 04:00.0 chip-ID: 10ec:8168
  IF: enp4s0 state: down mac: <filter>
  Device-2: Intel Wireless-AC 9260 driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1
    bus-ID: 05:00.0 chip-ID: 8086:2526
  IF: wlp5s0 state: down mac: <filter>
  Device-3: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: d000 bus-ID: 06:00.0 chip-ID: 10ec:8168
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 9260 Bluetooth Adapter type: USB driver: btusb v: 0.8 bus-ID: 3-5:2
    chip-ID: 8087:0025
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0 lmp-v: 5.1
    sub-v: 100
Drives:
  Local Storage: total: 5.46 TiB used: 636.4 GiB (11.4%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 PRO 2TB size: 1.82 TiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 42.9 C
  ID-2: /dev/sda vendor: Western Digital model: WD40EFAX-68JH4N1 size: 3.64 TiB speed: 6.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 1.79 TiB used: 635.67 GiB (34.7%) fs: ext4 dev: /dev/dm-1 mapped: vgmint-root
  ID-2: /boot size: 1.61 GiB used: 737.9 MiB (44.9%) fs: ext4 dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 976 MiB used: 0 KiB (0.0%) priority: -2 dev: /dev/dm-2
    mapped: vgmint-swap_1
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 6 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Hub-2: 1-2:2 info: Hitachi ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 045b:0209
  Hub-3: 1-2.1:4 info: Hitachi ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 045b:0209
  Hub-4: 1-2.1.3:7 info: Hitachi ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 045b:0209
  Hub-5: 1-2.1.3.1:8 info: Hitachi ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 045b:0209
  Device-1: 1-2.1.3.2:9 info: Microsoft Xbox360 Controller type: <vendor specific> driver: xpad
    rev: 2.0 speed: 12 Mb/s chip-ID: 045e:028e
  Device-2: 1-2.4:5 info: Logitech HD Pro Webcam C920 type: Video,Audio
    driver: snd-usb-audio,uvcvideo rev: 2.0 speed: 480 Mb/s chip-ID: 046d:082d
  Hub-6: 1-5:3 info: Terminus Hub ports: 4 rev: 2.0 speed: 480 Mb/s chip-ID: 1a40:0101
  Device-1: 1-5.4:6 info: Realtek Mass Storage Device (Multicard Reader) type: Mass Storage
    driver: usb-storage rev: 2.0 speed: 480 Mb/s chip-ID: 0bda:0151
  Hub-7: 2-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
  Hub-8: 2-2:2 info: Hitachi ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 045b:0210
  Hub-9: 2-2.1:3 info: Hitachi ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 045b:0210
  Hub-10: 2-2.1.3:4 info: Hitachi ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 045b:0210
  Hub-11: 2-2.1.3.1:5 info: Hitachi ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 045b:0210
  Hub-12: 3-0:1 info: Hi-speed hub with single TT ports: 6 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Device-1: 3-5:2 info: Intel Wireless-AC 9260 Bluetooth Adapter type: Bluetooth driver: btusb
    rev: 2.0 speed: 12 Mb/s chip-ID: 8087:0025
  Device-2: 3-6:3 info: ASUSTek AURA LED Controller type: HID driver: hid-generic,usbhid
    rev: 2.0 speed: 12 Mb/s chip-ID: 0b05:18f3
  Hub-13: 4-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
  Hub-14: 5-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Device-1: 5-3:2 info: Megawin Defender Gaming Keyboard type: Keyboard
    driver: hid-generic,usbhid rev: 1.1 speed: 1.5 Mb/s chip-ID: 0e6a:02c0
  Device-2: 5-4:3 info: Sunplus Innovation Gaming mouse [Philips SPK9304] type: Mouse
    driver: hid-generic,usbhid rev: 2.0 speed: 1.5 Mb/s chip-ID: 1bcf:08a0
  Hub-15: 6-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 48 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 3090 apt: 3076 flatpak: 14
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/insync.list
    1: deb http: //apt.insync.io/mint vera non-free contrib
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 520 Uptime: 8h 33m Memory: 31.25 GiB used: 9.06 GiB (29.0%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Unknown python3.10 client inxi: 3.3.13
```

Jesse

**Comment by JesseLeePalser** [comment] 2023-07-02 06:05
![Screenshot-01](https://github.com/linuxmint/mint21.2-beta/assets/138352613/78ae74b7-5b75-4c20-9ecd-b9157cc5203b)

**Comment by clefebvre** [comment] 2023-07-02 09:40
Version 535 is being phased in by Ubuntu right now to replace 530. You're probably pointing at a 530 candidate which no longer exists other than as a transitional package but with a 535 which isn't completely phased in yet.

`apt policy nvidia-driver-535`

Mine's phased at 60% here for instance.

You can force the update manually probably or troubleshoot it:

`apt install nvidia-driver-530 --dry-run`

I'll close the issue since it's just a temporary update being worked on, not a bug on mintdrivers.

**Closed as completed by clefebvre** 2023-07-02 09:40 UTC
